### ISSUE TITLE
Styling 

### ISSUE THREAD

**Issue by damareray** [campaignzero/campaign-zero-widget#15]
Hi, I need to add this widget to my website but i need to change colors for button and background. I'm not a coder so i couldn't find how to do it. Do you have any tips?

Thank's in advance

**Comment by manifestinteractive** [comment]
You will need to find someone that is a coder / designer for this.  Specifically, you will need to find someone that knows CSS.  They will need to create CSS that looks something like this on your website:

```css
#campaign-zero-widget {
    background-color: #FFFFFF !important;
}
#campaign-zero-widget button {
    background-color: #000000 !important;
    border-color: #000000 !important;
    color: #FFFFFF !important;
}
```
